### ISSUE TITLE
Error Creating User

### ISSUE THREAD

**Issue by axellfumioo** [hcgcloud/pterodactyl-sdk#43]
`Fatal error: Uncaught HCGCloud\Pterodactyl\Exceptions\ValidationException: The given data failed to pass validation. in D:\**\php\database\vendor\hcgcloud\pterodactyl-sdk\src\MakesHttpRequests.php:117 Stack trace: #0 D:\**\php\database\vendor\hcgcloud\pterodactyl-sdk\src\MakesHttpRequests.php(101): HCGCloud\Pterodactyl\Pterodactyl->handleRequestError(Object(GuzzleHttp\Psr7\Response)) #1 D:\**\php\database\vendor\hcgcloud\pterodactyl-sdk\src\MakesHttpRequests.php(35): HCGCloud\Pterodactyl\Pterodactyl->request('POST', 'api/application...', Array) #2 D:\**\php\database\vendor\hcgcloud\pterodactyl-sdk\src\Actions\ManagesUsers.php(56): HCGCloud\Pterodactyl\Pterodactyl->post('api/application...', Array) #3 D:\**\php\database\register-handler.php(61): HCGCloud\Pterodactyl\Pterodactyl->createUser(Array) #4 {main} thrown in D:\**\php\database\vendor\hcgcloud\pterodactyl-sdk\src\MakesHttpRequests.php on line 117`

Can some one help me?

**Comment by axellfumioo** [comment]
Request Code:
```
        $user = $pterodactyl->createUser([
            'email' => $filterEmail,
            'username' => $inputUsername,
            'password' => $inputPassword,
            'language' => 'en',
            'root_admin' => false,
            'first_name' => $inputUsername,
            'last_name' => 'Client'
        ]);
```

**Comment by sudo-arash** [comment]
Hmm... Maybe your fields are null. Have you tried to check that?
